kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: customers-deployment
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: customers
      spec:
        containers:
        - name: customers
          image: jagannathbalachandran/customers:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config/customers
          env:
          - name: SPRING_CONFIG_LOCATION
            value: /etc/config/customers/application.properties
        volumes:
        - name: config-volume
          configMap:
            name: shopper-config
            items:
            - key: customers.properties
              path: application.properties
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: orders-deployment
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: orders
      spec:
        containers:
        - name: orders
          image: jagannathbalachandran/orders:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config/orders
          env:
          - name: SPRING_CONFIG_LOCATION
            value: /etc/config/orders/application.properties
        volumes:
        - name: config-volume
          configMap:
            name: shopper-config
            items:
            - key: orders.properties
              path: application.properties
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: activemq-deployment
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: activemq
      spec:
        containers:
        - name: activemq
          image: webcenter/activemq:5.14.2
          ports:
          - name: broker
            containerPort: 61616
          - name: admin
            containerPort: 8161