version: '2'
services:
  customers:
    image: jagannathbalachandran/customers
    ports:
    - "8081:8080"
    environment:
    - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
  orders:
    image: jagannathbalachandran/orders
    ports:
    - "8082:8080"
    environment:
    - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
  activemq:
    build: activemq
    ports:
    - "8161:8161"
    volumes:
    - /var/log/activemq
    - /var/data/activemq